import type { AppState } from "./types";

const now = "2026-09-05T08:30:00.000Z";

export const seedState: AppState = {
  currentUserId: null,
  settings: {
    locale: "en",
    defaultCity: "Jigjiga",
    defaultRegion: "Somali",
    notificationsEnabled: true,
  },
  users: [
    {
      id: "user_admin",
      fullName: "Amina Yusuf",
      phone: "251911000001",
      email: "admin@farsamo.et",
      password: "admin123",
      role: "admin",
      status: "active",
      city: "Jigjiga",
      region: "Somali",
      area: "Kebele 04",
      avatarUrl: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=200&q=80",
      createdAt: "2025-11-02T09:00:00.000Z",
    },
    {
      id: "user_ahmed",
      fullName: "Ahmed Ali",
      phone: "251912345678",
      email: "ahmed.ali@email.com",
      password: "farsamo123",
      role: "customer",
      status: "active",
      city: "Jigjiga",
      region: "Somali",
      area: "Kebele 06",
      avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80",
      createdAt: "2026-02-14T10:00:00.000Z",
    },
    {
      id: "user_hawa",
      fullName: "Hawa Osman",
      phone: "251913456789",
      password: "farsamo123",
      role: "customer",
      status: "active",
      city: "Jigjiga",
      region: "Somali",
      area: "Kebele 02",
      createdAt: "2026-03-08T12:20:00.000Z",
    },
    {
      id: "user_tigist",
      fullName: "Tigist Haile",
      phone: "251914567890",
      password: "farsamo123",
      role: "customer",
      status: "active",
      city: "Addis Ababa",
      region: "Addis Ababa",
      area: "Bole",
      createdAt: "2026-04-19T08:15:00.000Z",
    },
    {
      id: "user_mohamed",
      fullName: "Mohamed Abdi",
      phone: "251915678901",
      password: "farsamo123",
      role: "customer",
      status: "blocked",
      city: "Dire Dawa",
      region: "Dire Dawa",
      area: "Kezira",
      createdAt: "2026-01-22T16:40:00.000Z",
    },
    {
      id: "user_sara",
      fullName: "Sara Tesfaye",
      phone: "251916789012",
      password: "farsamo123",
      role: "customer",
      status: "active",
      city: "Harar",
      region: "Harari",
      area: "Jegol",
      createdAt: "2026-05-03T11:05:00.000Z",
    },
  ],
  providers: [
    {
      id: "prov_ahmed_hassan",
      fullName: "Ahmed Hassan",
      phone: "251917111222",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      profession: "Plumber",
      skills: ["Leak repair", "Pipe installation", "Bathroom fixtures"],
      description: "Licensed plumber serving homes and small shops across Jigjiga.",
      experienceYears: 8,
      city: "Jigjiga",
      region: "Somali",
      address: "Kebele 05, near Central Market",
      serviceArea: "Jigjiga city and nearby kebeles",
      status: "approved",
      availability: "available",
      rating: 4.8,
      completedJobs: 146,
      createdAt: "2025-12-01T09:00:00.000Z",
    },
    {
      id: "prov_fatima",
      fullName: "Fatima Mohamed",
      phone: "251917222333",
      avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
      profession: "Electrician",
      skills: ["Wiring", "Socket repair", "Lighting"],
      description: "Residential electrician with a focus on safe home wiring.",
      experienceYears: 6,
      city: "Jigjiga",
      region: "Somali",
      address: "Kebele 03",
      serviceArea: "Jigjiga",
      status: "approved",
      availability: "available",
      rating: 4.7,
      completedJobs: 98,
      createdAt: "2026-01-10T09:00:00.000Z",
    },
    {
      id: "prov_dawit",
      fullName: "Dawit Bekele",
      phone: "251917333444",
      avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80",
      profession: "AC Technician",
      skills: ["Split AC", "Gas refill", "Cleaning"],
      description: "Air conditioning installation and repair for homes and offices.",
      experienceYears: 10,
      city: "Addis Ababa",
      region: "Addis Ababa",
      address: "Kirkos",
      serviceArea: "Addis Ababa",
      status: "approved",
      availability: "busy",
      rating: 4.9,
      completedJobs: 210,
      createdAt: "2025-10-18T09:00:00.000Z",
    },
    {
      id: "prov_yunus",
      fullName: "Yunus Ibrahim",
      phone: "251917444555",
      profession: "Auto Mechanic",
      skills: ["Engine", "Brakes", "Oil change"],
      description: "Mobile car mechanic covering Jigjiga and the highway corridor.",
      experienceYears: 12,
      city: "Jigjiga",
      region: "Somali",
      address: "Industrial Zone",
      serviceArea: "Jigjiga and Tog Wajale road",
      status: "approved",
      availability: "available",
      rating: 4.6,
      completedJobs: 187,
      createdAt: "2026-02-02T09:00:00.000Z",
    },
    {
      id: "prov_leila",
      fullName: "Leila Farah",
      phone: "251917555666",
      profession: "Phone Technician",
      skills: ["Screen replacement", "Battery", "Software"],
      description: "Phone and tablet repair with same-day turnaround when parts are ready.",
      experienceYears: 5,
      city: "Dire Dawa",
      region: "Dire Dawa",
      address: "Taiwan",
      serviceArea: "Dire Dawa",
      status: "pending",
      availability: "offline",
      rating: 0,
      completedJobs: 0,
      createdAt: "2026-08-28T09:00:00.000Z",
    },
    {
      id: "prov_solomon",
      fullName: "Solomon Getachew",
      phone: "251917666777",
      profession: "Painter",
      skills: ["Interior", "Exterior", "Waterproofing"],
      description: "House painting crews for apartments and new builds.",
      experienceYears: 9,
      city: "Hawassa",
      region: "Sidama",
      address: "Piazza",
      serviceArea: "Hawassa",
      status: "suspended",
      availability: "offline",
      rating: 4.4,
      completedJobs: 64,
      createdAt: "2026-03-12T09:00:00.000Z",
    },
  ],
  categories: [
    { id: "cat_home", name: "Home Services", slug: "home", description: "Plumbing, electrical and household repairs.", icon: "House", color: "#F59E0B", isEnabled: true, sortOrder: 1, createdAt: now },
    { id: "cat_electronics", name: "Electronics", slug: "electronics", description: "Phones, computers and appliances.", icon: "Smartphone", color: "#8B5CF6", isEnabled: true, sortOrder: 2, createdAt: now },
    { id: "cat_vehicle", name: "Vehicle", slug: "vehicle", description: "Car and motorcycle repair.", icon: "Car", color: "#2563EB", isEnabled: true, sortOrder: 3, createdAt: now },
    { id: "cat_cleaning", name: "Cleaning", slug: "cleaning", description: "Home and office cleaning.", icon: "Sparkles", color: "#10B981", isEnabled: true, sortOrder: 4, createdAt: now },
    { id: "cat_construction", name: "Construction", slug: "construction", description: "Building, painting and carpentry.", icon: "HardHat", color: "#F97316", isEnabled: true, sortOrder: 5, createdAt: now },
  ],
  services: [
    {
      id: "svc_plumbing",
      name: "Plumbing",
      categoryId: "cat_home",
      shortDescription: "Pipes, leaks and fixture installation.",
      description: "Professional plumbing for kitchens, bathrooms and water lines. Includes leak repair, pipe installation, tap replacement and blocked drain clearing.",
      startingPrice: 300,
      estimatedTime: "1-2 hours",
      images: [
        "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
      ],
      isAvailable: true,
      rating: 4.8,
      reviewCount: 120,
      isPopular: true,
      isFeatured: true,
      createdAt: "2026-01-05T09:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "svc_electrical",
      name: "Electrical",
      categoryId: "cat_home",
      shortDescription: "Wiring, sockets and lighting.",
      description: "Safe electrical repair for homes and small businesses, from blown sockets to full room lighting upgrades.",
      startingPrice: 350,
      estimatedTime: "1-3 hours",
      images: [
        "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1558618047-f4b511aee6d1?auto=format&fit=crop&w=800&q=80",
      ],
      isAvailable: true,
      rating: 4.7,
      reviewCount: 86,
      isPopular: true,
      isFeatured: false,
      createdAt: "2026-01-05T09:10:00.000Z",
      updatedAt: now,
    },
    {
      id: "svc_ac",
      name: "AC Repair",
      categoryId: "cat_home",
      shortDescription: "Cooling, gas refill and servicing.",
      description: "Split and window AC cleaning, gas refill, installation and fault diagnosis for the hot season.",
      startingPrice: 500,
      estimatedTime: "2-4 hours",
      images: [
        "https://images.unsplash.com/photo-1631545806609-35c1962c0bae?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1615876234886-fd9a39fda97f?auto=format&fit=crop&w=800&q=80",
      ],
      isAvailable: true,
      rating: 4.6,
      reviewCount: 64,
      isPopular: true,
      isFeatured: true,
      createdAt: "2026-01-06T09:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "svc_fridge",
      name: "Refrigerator Repair",
      categoryId: "cat_electronics",
      shortDescription: "Cooling issues and thermostat repair.",
      description: "Fridge and freezer repair including compressor checks, thermostat replacement and gas work.",
      startingPrice: 400,
      estimatedTime: "2-3 hours",
      images: [
        "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=1200&q=80",
      ],
      isAvailable: true,
      rating: 4.5,
      reviewCount: 41,
      isPopular: false,
      isFeatured: false,
      createdAt: "2026-01-07T09:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "svc_phone",
      name: "Phone Repair",
      categoryId: "cat_electronics",
      shortDescription: "Screens, batteries and charging ports.",
      description: "Mobile phone repair for cracked screens, battery drain, charging faults and water damage assessment.",
      startingPrice: 250,
      estimatedTime: "45-90 minutes",
      images: [
        "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
      ],
      isAvailable: true,
      rating: 4.4,
      reviewCount: 73,
      isPopular: true,
      isFeatured: false,
      createdAt: "2026-01-08T09:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "svc_computer",
      name: "Computer Repair",
      categoryId: "cat_electronics",
      shortDescription: "Laptops, software and hardware.",
      description: "Laptop and desktop repair, OS setup, virus cleanup and hardware upgrades.",
      startingPrice: 300,
      estimatedTime: "1-3 hours",
      images: [
        "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200&q=80",
      ],
      isAvailable: true,
      rating: 4.5,
      reviewCount: 52,
      isPopular: false,
      isFeatured: true,
      createdAt: "2026-01-08T09:20:00.000Z",
      updatedAt: now,
    },
    {
      id: "svc_car",
      name: "Car Repair",
      categoryId: "cat_vehicle",
      shortDescription: "Mobile mechanic for common faults.",
      description: "On-site car diagnostics, oil change, brake work and battery jump or replacement.",
      startingPrice: 800,
      estimatedTime: "2-5 hours",
      images: [
        "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=1200&q=80",
      ],
      isAvailable: true,
      rating: 4.6,
      reviewCount: 91,
      isPopular: true,
      isFeatured: true,
      createdAt: "2026-01-09T09:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "svc_cleaning",
      name: "Cleaning",
      categoryId: "cat_cleaning",
      shortDescription: "Home and office deep cleaning.",
      description: "Scheduled home cleaning, move-in cleaning and office floor care with trained teams.",
      startingPrice: 400,
      estimatedTime: "2-4 hours",
      images: [
        "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80",
      ],
      isAvailable: true,
      rating: 4.7,
      reviewCount: 58,
      isPopular: false,
      isFeatured: false,
      createdAt: "2026-01-10T09:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "svc_painting",
      name: "Painting",
      categoryId: "cat_construction",
      shortDescription: "Interior and exterior painting.",
      description: "Room refresh, full-house painting and exterior weatherproof coats.",
      startingPrice: 600,
      estimatedTime: "1-2 days",
      images: [
        "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=1200&q=80",
      ],
      isAvailable: true,
      rating: 4.3,
      reviewCount: 37,
      isPopular: false,
      isFeatured: false,
      createdAt: "2026-01-11T09:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "svc_carpentry",
      name: "Carpentry",
      categoryId: "cat_construction",
      shortDescription: "Doors, shelves and furniture repair.",
      description: "Custom shelves, door alignment, kitchen fittings and wood repair.",
      startingPrice: 450,
      estimatedTime: "2-6 hours",
      images: [
        "https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=1200&q=80",
      ],
      isAvailable: false,
      rating: 4.2,
      reviewCount: 19,
      isPopular: false,
      isFeatured: false,
      createdAt: "2026-01-12T09:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "svc_construction",
      name: "Construction",
      categoryId: "cat_construction",
      shortDescription: "Small builds and site support.",
      description: "Small construction jobs, wall repair, tiling support and site labour coordination.",
      startingPrice: 1500,
      estimatedTime: "1-5 days",
      images: [
        "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80",
      ],
      isAvailable: true,
      rating: 4.4,
      reviewCount: 28,
      isPopular: false,
      isFeatured: false,
      createdAt: "2026-01-13T09:00:00.000Z",
      updatedAt: now,
    },
  ],
  requests: [
    {
      id: "req_001",
      requestNumber: "FS-20260905-001",
      customerId: "user_ahmed",
      serviceId: "svc_plumbing",
      description: "Water leak under the kitchen sink. The cabinet floor is wet.",
      images: [
        "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=600&q=80",
      ],
      location: {
        region: "Somali",
        city: "Jigjiga",
        area: "Kebele 06",
        address: "House 24, near Sheik Abdisalan Mosque",
      },
      preferredDate: "2026-09-05",
      preferredTime: "14:00",
      phone: "251912345678",
      status: "pending",
      adminNotes: [],
      createdAt: "2026-09-05T07:40:00.000Z",
      updatedAt: "2026-09-05T07:40:00.000Z",
    },
    {
      id: "req_002",
      requestNumber: "FS-20260904-003",
      customerId: "user_hawa",
      serviceId: "svc_electrical",
      description: "Two sockets in the living room stopped working after a power cut.",
      images: [],
      location: {
        region: "Somali",
        city: "Jigjiga",
        area: "Kebele 02",
        address: "Behind Jigjiga University gate",
      },
      preferredDate: "2026-09-04",
      preferredTime: "10:30",
      phone: "251913456789",
      status: "provider_assigned",
      assignedProviderId: "prov_fatima",
      adminNotes: [
        {
          id: "note_001",
          requestId: "req_002",
          authorId: "user_admin",
          message: "Assigned Fatima. Customer prefers morning visit.",
          createdAt: "2026-09-04T09:10:00.000Z",
        },
      ],
      createdAt: "2026-09-04T08:05:00.000Z",
      updatedAt: "2026-09-04T09:10:00.000Z",
    },
    {
      id: "req_003",
      requestNumber: "FS-20260903-012",
      customerId: "user_tigist",
      serviceId: "svc_ac",
      description: "Bedroom AC is blowing warm air.",
      images: [],
      location: {
        region: "Addis Ababa",
        city: "Addis Ababa",
        area: "Bole",
        address: "Bole Atlas, apartment 3B",
      },
      preferredDate: "2026-09-03",
      preferredTime: "16:00",
      phone: "251914567890",
      status: "on_the_way",
      assignedProviderId: "prov_dawit",
      adminNotes: [],
      createdAt: "2026-09-03T11:20:00.000Z",
      updatedAt: "2026-09-03T15:10:00.000Z",
    },
    {
      id: "req_004",
      requestNumber: "FS-20260828-008",
      customerId: "user_ahmed",
      serviceId: "svc_car",
      description: "Car battery died near the market. Need jump start and check.",
      images: [],
      location: {
        region: "Somali",
        city: "Jigjiga",
        area: "Kebele 04",
        address: "Central Market parking",
      },
      preferredDate: "2026-08-28",
      preferredTime: "09:00",
      phone: "251912345678",
      status: "completed",
      assignedProviderId: "prov_yunus",
      adminNotes: [],
      createdAt: "2026-08-28T06:50:00.000Z",
      updatedAt: "2026-08-28T11:20:00.000Z",
    },
    {
      id: "req_005",
      requestNumber: "FS-20260820-004",
      customerId: "user_sara",
      serviceId: "svc_cleaning",
      description: "Need a full house clean before guests arrive on Friday.",
      images: [],
      location: {
        region: "Harari",
        city: "Harar",
        area: "Jegol",
        address: "Near Arthur Rimbaud house",
      },
      preferredDate: "2026-08-21",
      preferredTime: "08:00",
      phone: "251916789012",
      status: "cancelled",
      adminNotes: [
        {
          id: "note_002",
          requestId: "req_005",
          authorId: "user_admin",
          message: "Customer cancelled after changing travel dates.",
          createdAt: "2026-08-20T14:00:00.000Z",
        },
      ],
      createdAt: "2026-08-20T09:00:00.000Z",
      updatedAt: "2026-08-20T14:00:00.000Z",
    },
    {
      id: "req_006",
      requestNumber: "FS-20260905-002",
      customerId: "user_hawa",
      serviceId: "svc_phone",
      description: "Cracked screen on Samsung A14. Touch still works.",
      images: [],
      location: {
        region: "Somali",
        city: "Jigjiga",
        area: "Kebele 02",
        address: "Kebele 02, house 11",
      },
      preferredDate: "2026-09-06",
      preferredTime: "11:00",
      phone: "251913456789",
      status: "under_review",
      adminNotes: [],
      createdAt: "2026-09-05T08:05:00.000Z",
      updatedAt: "2026-09-05T08:20:00.000Z",
    },
  ],
  reviews: [
    {
      id: "rev_001",
      requestId: "req_004",
      customerId: "user_ahmed",
      serviceId: "svc_car",
      rating: 5,
      comment: "Yunus arrived quickly and the car started on the first try. Fair price.",
      createdAt: "2026-08-28T12:00:00.000Z",
    },
  ],
  notifications: [
    {
      id: "ntf_001",
      audience: "customer",
      userId: "user_ahmed",
      title: "Request received",
      message: "FS-20260905-001 is pending review. We will assign a provider shortly.",
      requestId: "req_001",
      isRead: false,
      createdAt: "2026-09-05T07:40:00.000Z",
    },
    {
      id: "ntf_002",
      audience: "admin",
      title: "New service request",
      message: "Ahmed Ali submitted a plumbing request in Jigjiga.",
      requestId: "req_001",
      isRead: false,
      createdAt: "2026-09-05T07:40:00.000Z",
    },
    {
      id: "ntf_003",
      audience: "customer",
      userId: "user_hawa",
      title: "Provider assigned",
      message: "A service provider has been assigned to FS-20260904-003.",
      requestId: "req_002",
      isRead: true,
      createdAt: "2026-09-04T09:10:00.000Z",
    },
  ],
  media: [
    {
      id: "media_001",
      kind: "banner",
      name: "Home hero",
      url: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80",
      isActive: true,
      createdAt: now,
    },
    {
      id: "media_002",
      kind: "service",
      name: "Plumbing cover",
      url: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=1200&q=80",
      isActive: true,
      createdAt: now,
    },
  ],
  payments: [
    {
      id: "pay_001",
      requestId: "req_004",
      customerId: "user_ahmed",
      amount: 850,
      currency: "ETB",
      status: "paid",
      method: "Telebirr",
      createdAt: "2026-08-28T11:25:00.000Z",
    },
  ],
};
